name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mongo_db:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: amalfranci/datas-backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: amalfranci/datas-frontend:latest

    - name: Start containers
      run: |
        docker-compose -f docker-compose.yaml up -d
        sleep 30  # Ensure all services are up

    - name: Wait for MongoDB to be ready
      run: |
        until docker-compose -f docker-compose.yaml run --rm mongo_db mongosh --eval 'db.runCommand("ping").ok'; do
          echo "Waiting for MongoDB to be ready..."
          sleep 10
        done

    - name: Check backend container logs
      run: docker-compose -f docker-compose.yaml logs backend

    - name: Check MongoDB logs
      run: docker-compose -f docker-compose.yaml logs mongo_db

    - name: Run backend tests
      run: |
        docker-compose -f docker-compose.yaml run backend npm test
      env:
        MONGODB_URI: mongodb://mongo_db:27017/my_db

    - name: Stop and remove containers
      run: docker-compose -f docker-compose.yaml down
